version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      # Check for npm updates on Sundays
      day: 'sunday'
    # Raise pull requests for version updates
    # to npm against the `develop` branch
    target-branch: 'develop'
    # Labels on pull requests for security and version updates
    labels:
      - 'npm'
      - 'dependencies'
